"""
Mock 데이터 - 백엔드 API 대체
실제 프로젝트의 백엔드 API 응답 구조를 그대로 모방
"""

MOCK_PETS = [
    # ── 서울 ──────────────────────────────────────
    {
        "petId": 1,
        "name": "코코",
        "breed": "말티즈",
        "age": 2,
        "gender": "FEMALE",
        "location": "서울 마포구",
        "personality": "온순하고 차분한 성격, 사람을 잘 따름",
        "description": "조용한 환경을 좋아하는 얌전한 아이입니다",
        "weight": 3.2,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 2,
        "name": "콩이",
        "breed": "포메라니안",
        "age": 1,
        "gender": "MALE",
        "location": "서울 강남구",
        "personality": "장난기 많고 활발함, 호기심이 많음",
        "description": "어린 강아지로 활기차고 귀여운 아이입니다",
        "weight": 2.8,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 3,
        "name": "하루",
        "breed": "시츄",
        "age": 6,
        "gender": "FEMALE",
        "location": "서울 송파구",
        "personality": "온순하고 조용함, 실내 생활에 적합",
        "description": "나이가 있지만 건강하고 온순한 성격의 아이입니다",
        "weight": 5.5,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 4,
        "name": "솜이",
        "breed": "푸들",
        "age": 3,
        "gender": "FEMALE",
        "location": "서울 서초구",
        "personality": "영리하고 온순함, 훈련을 잘 따름",
        "description": "지능이 높고 사람을 잘 따르는 영리한 아이입니다",
        "weight": 4.5,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 5,
        "name": "달이",
        "breed": "코기",
        "age": 4,
        "gender": "MALE",
        "location": "서울 종로구",
        "personality": "활발하고 영리함, 장난치는 걸 좋아함",
        "description": "짧은 다리지만 에너지 넘치는 귀여운 아이입니다",
        "weight": 13.0,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 6,
        "name": "아톰",
        "breed": "저먼셰퍼드",
        "age": 5,
        "gender": "MALE",
        "location": "서울 강동구",
        "personality": "충성스럽고 보호 본능 강함, 훈련 수행 능력 뛰어남",
        "description": "넓은 공간에서 활발하게 생활하는 듬직한 아이입니다",
        "weight": 32.0,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    # ── 경기 ──────────────────────────────────────
    {
        "petId": 7,
        "name": "나비",
        "breed": "치와와",
        "age": 2,
        "gender": "FEMALE",
        "location": "경기 성남시",
        "personality": "겁은 많지만 가족에게 애교가 넘침, 온순함",
        "description": "작지만 당찬 매력을 가진 소형견입니다",
        "weight": 2.1,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 8,
        "name": "루비",
        "breed": "요크셔테리어",
        "age": 3,
        "gender": "FEMALE",
        "location": "경기 안양시",
        "personality": "활발하고 애교 많음, 주인에게 충성스러움",
        "description": "실크처럼 부드러운 털을 가진 사랑스러운 아이입니다",
        "weight": 2.5,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 9,
        "name": "토리",
        "breed": "비글",
        "age": 2,
        "gender": "MALE",
        "location": "경기 수원시",
        "personality": "호기심 많고 사교적, 냄새 맡는 것을 좋아함",
        "description": "산책을 좋아하는 활발하고 명랑한 아이입니다",
        "weight": 9.8,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 10,
        "name": "맥스",
        "breed": "골든리트리버",
        "age": 4,
        "gender": "MALE",
        "location": "경기 수원시",
        "personality": "활발하고 에너지 넘침, 운동을 좋아함",
        "description": "대형견으로 넓은 공간이 필요한 활발한 아이입니다",
        "weight": 30.5,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 11,
        "name": "보리",
        "breed": "진돗개",
        "age": 5,
        "gender": "MALE",
        "location": "경기 고양시",
        "personality": "충성스럽고 활발함, 주인에게 헌신적",
        "description": "한국 토종견으로 건강하고 충성심 강한 아이입니다",
        "weight": 18.0,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 12,
        "name": "흰둥이",
        "breed": "사모예드",
        "age": 8,
        "gender": "MALE",
        "location": "경기 용인시",
        "personality": "온순하고 친화력 좋음, 노령이지만 건강함",
        "description": "시니어견으로 조용하고 편안한 가정을 원하는 아이입니다",
        "weight": 25.0,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": "정기 관절 관리 필요",
    },
    # ── 부산 ──────────────────────────────────────
    {
        "petId": 13,
        "name": "별이",
        "breed": "말티즈",
        "age": 4,
        "gender": "FEMALE",
        "location": "부산 남구",
        "personality": "온순하고 애교가 많음, 실내 생활을 즐김",
        "description": "조용하고 사랑스러운 소형견입니다",
        "weight": 3.0,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 14,
        "name": "팥이",
        "breed": "포메라니안",
        "age": 2,
        "gender": "MALE",
        "location": "부산 동래구",
        "personality": "활발하고 밝음, 낯선 사람에게도 친근하게 다가감",
        "description": "폭신한 털과 귀여운 외모로 인기 만점인 아이입니다",
        "weight": 2.6,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 15,
        "name": "두부",
        "breed": "비글",
        "age": 3,
        "gender": "FEMALE",
        "location": "부산 해운대구",
        "personality": "활동적이고 사교적, 아이들과 잘 어울림",
        "description": "가족 모두와 잘 어울리는 사교적인 아이입니다",
        "weight": 10.2,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 16,
        "name": "구름",
        "breed": "시베리안허스키",
        "age": 3,
        "gender": "MALE",
        "location": "부산 사하구",
        "personality": "독립적이고 활동적, 운동량이 많음",
        "description": "눈처럼 흰 털과 파란 눈이 매력적인 아이입니다",
        "weight": 26.0,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 17,
        "name": "초코",
        "breed": "래브라도",
        "age": 1,
        "gender": "FEMALE",
        "location": "부산 수영구",
        "personality": "에너지 넘치고 사교적, 어린 강아지 특유의 호기심",
        "description": "어리고 활발한 퍼피로 넓은 사랑을 줄 가정을 찾고 있습니다",
        "weight": 15.0,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    # ── 인천 ──────────────────────────────────────
    {
        "petId": 18,
        "name": "모모",
        "breed": "시츄",
        "age": 5,
        "gender": "FEMALE",
        "location": "인천 부평구",
        "personality": "온순하고 애교가 많음, 조용한 성격",
        "description": "실내 생활에 최적화된 조용하고 사랑스러운 아이입니다",
        "weight": 6.0,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 19,
        "name": "단추",
        "breed": "코기",
        "age": 2,
        "gender": "MALE",
        "location": "인천 연수구",
        "personality": "활발하고 장난기 많음, 아이들과 잘 놂",
        "description": "짧은 다리로 귀엽게 뛰어다니는 활발한 아이입니다",
        "weight": 12.3,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 20,
        "name": "복이",
        "breed": "래브라도",
        "age": 6,
        "gender": "MALE",
        "location": "인천 남동구",
        "personality": "온순하고 친화력 좋음, 어린이와 잘 어울림",
        "description": "순하고 듬직한 대형견으로 가족 모두에게 사랑받는 아이입니다",
        "weight": 28.0,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    # ── 대구 ──────────────────────────────────────
    {
        "petId": 21,
        "name": "솔이",
        "breed": "푸들",
        "age": 1,
        "gender": "FEMALE",
        "location": "대구 수성구",
        "personality": "영리하고 활발함, 배우는 속도가 빠름",
        "description": "어린 나이에도 영특한 퍼피입니다",
        "weight": 3.8,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 22,
        "name": "땅콩",
        "breed": "비글",
        "age": 4,
        "gender": "MALE",
        "location": "대구 달서구",
        "personality": "명랑하고 고집스러움, 특유의 하울링을 가끔 함",
        "description": "활동적이고 탐구심 강한 중형견입니다",
        "weight": 11.5,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 23,
        "name": "호두",
        "breed": "골든리트리버",
        "age": 2,
        "gender": "MALE",
        "location": "대구 북구",
        "personality": "온순하고 사교적, 아이들을 좋아함",
        "description": "황금빛 털이 아름다운 상냥한 대형견입니다",
        "weight": 29.0,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    # ── 대전 ──────────────────────────────────────
    {
        "petId": 24,
        "name": "미미",
        "breed": "말티즈",
        "age": 3,
        "gender": "FEMALE",
        "location": "대전 유성구",
        "personality": "차분하고 온순함, 혼자 있는 시간도 잘 견딤",
        "description": "독립적이면서도 사랑스러운 소형견입니다",
        "weight": 3.5,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 25,
        "name": "바둑이",
        "breed": "코기",
        "age": 5,
        "gender": "MALE",
        "location": "대전 서구",
        "personality": "활달하고 영리함, 운동과 산책을 매우 좋아함",
        "description": "특유의 귀여운 엉덩이로 사랑받는 아이입니다",
        "weight": 14.0,
        "vaccinated": True,
        "neutered": False,
        "adopted": False,
        "specialNeeds": None,
    },
    {
        "petId": 26,
        "name": "태풍",
        "breed": "저먼셰퍼드",
        "age": 4,
        "gender": "MALE",
        "location": "대전 동구",
        "personality": "충성스럽고 보호 본능 강함, 가족에게 헌신적",
        "description": "듬직하고 믿음직스러운 대형견입니다",
        "weight": 33.0,
        "vaccinated": True,
        "neutered": True,
        "adopted": False,
        "specialNeeds": None,
    },
]

MOCK_INSURANCES = [
    {
        "insuranceId": 1,
        "company": "현대해상",
        "productName": "하이펫 반려견 보험 기본형",
        "description": "소형견 전용 기본 보장, 슬개골 탈구 및 치아 질환 보장",
        "features": ["슬개골 탈구 보장", "치아 질환 보장", "통원비 지원", "예방접종 할인"],
        "coverageDetails": ["수술비 최대 100만원", "입원비 하루 5만원", "통원비 회당 2만원"],
        "monthlyPremium": 25000,
    },
    {
        "insuranceId": 2,
        "company": "DB손해보험",
        "productName": "마이펫 종합 보험",
        "description": "모든 품종 가입 가능한 종합 보험, 수술 및 입원 집중 보장",
        "features": ["수술비 집중 보장", "암 보장", "응급 진료 보장", "24시간 상담"],
        "coverageDetails": ["수술비 최대 300만원", "암 진단금 50만원", "응급실 비용 전액 지원"],
        "monthlyPremium": 45000,
    },
    {
        "insuranceId": 3,
        "company": "삼성화재",
        "productName": "애니펫 시니어 케어",
        "description": "시니어견 전용, 만성 질환 및 관절 질환 집중 보장",
        "features": ["관절 질환 보장", "만성 질환 보장", "노령견 특화", "정기 건강검진 지원"],
        "coverageDetails": ["관절 수술비 최대 200만원", "만성 질환 치료비 월 10만원", "건강검진 연 2회"],
        "monthlyPremium": 55000,
    },
    {
        "insuranceId": 4,
        "company": "KB손해보험",
        "productName": "KB 반려견 실손 보험",
        "description": "대형견 전용 실손 보험, 고액 수술 및 입원비 집중 보장",
        "features": ["대형견 전용", "고액 수술 보장", "입원비 보장", "재활 치료 보장"],
        "coverageDetails": ["수술비 최대 500만원", "입원비 하루 10만원", "재활 치료비 지원"],
        "monthlyPremium": 65000,
    },
    {
        "insuranceId": 5,
        "company": "한화손해보험",
        "productName": "한화 펫사랑 퍼피 보험",
        "description": "1세 이하 어린 강아지 전용, 예방 및 기본 건강 보장",
        "features": ["퍼피 전용", "예방접종 보장", "기본 건강검진", "선천성 질환 보장"],
        "coverageDetails": ["예방접종비 전액 지원", "건강검진 연 3회", "선천성 질환 수술비 150만원"],
        "monthlyPremium": 20000,
    },
    {
        "insuranceId": 6,
        "company": "메리츠화재",
        "productName": "메리츠 반려견 피부·눈 전문 보험",
        "description": "피부 질환 및 눈 질환에 특화된 보험, 푸들·시츄 등 소형견 적합",
        "features": ["피부 질환 집중 보장", "눈 질환 보장", "알레르기 치료 지원", "외래 진료 지원"],
        "coverageDetails": ["피부 치료비 연 100만원", "눈 수술비 최대 150만원", "알레르기 검사비 지원"],
        "monthlyPremium": 30000,
    },
    {
        "insuranceId": 7,
        "company": "흥국화재",
        "productName": "흥국 반려견 종합 플러스",
        "description": "모든 품종 가입 가능, 입원·수술·통원 균형 있는 종합 보장",
        "features": ["종합 보장", "입원비 보장", "통원비 보장", "수술비 보장"],
        "coverageDetails": ["입원비 하루 7만원", "통원비 회당 3만원", "수술비 최대 250만원"],
        "monthlyPremium": 38000,
    },
    {
        "insuranceId": 8,
        "company": "NH농협손해보험",
        "productName": "NH 반려견 실속형 보험",
        "description": "합리적인 보험료로 기본 보장, 중소형견에 적합",
        "features": ["저렴한 보험료", "기본 수술 보장", "응급 진료 보장", "24시간 상담"],
        "coverageDetails": ["수술비 최대 80만원", "응급 진료비 50만원", "입원비 하루 3만원"],
        "monthlyPremium": 15000,
    },
]

MOCK_PRODUCTS = [
    {
        "productId": 1,
        "name": "로얄캐닌 말티즈 전용 사료 3kg",
        "description": "말티즈 품종 특성에 맞춘 소형견 전용 사료, 치아 건강 강화",
        "price": 38000,
        "category": "사료",
    },
    {
        "productId": 2,
        "name": "골든리트리버 관절 영양제",
        "description": "대형견 관절 건강을 위한 글루코사민 함유 영양제",
        "price": 45000,
        "category": "건강관리",
    },
    {
        "productId": 3,
        "name": "소형견 하네스 세트",
        "description": "소형견 체형에 맞는 안전 하네스 + 리드줄 세트",
        "price": 22000,
        "category": "용품",
    },
    {
        "productId": 4,
        "name": "강아지 노즈워크 장난감",
        "description": "후각 자극으로 두뇌 발달을 돕는 노즈워크 매트",
        "price": 18000,
        "category": "장난감",
    },
    {
        "productId": 5,
        "name": "프리미엄 강아지 침대 M사이즈",
        "description": "메모리폼 소재로 관절 보호, 세탁 가능한 커버",
        "price": 55000,
        "category": "용품",
    },
    {
        "productId": 6,
        "name": "강아지 천연 샴푸",
        "description": "민감한 피부를 위한 무향 천연 성분 샴푸",
        "price": 16000,
        "category": "미용",
    },
    {
        "productId": 7,
        "name": "대형견 스테인리스 식기 세트",
        "description": "미끄럼 방지 대형견용 밥그릇 + 물그릇 세트",
        "price": 28000,
        "category": "용품",
    },
    {
        "productId": 8,
        "name": "강아지 동결건조 간식 (닭가슴살)",
        "description": "첨가물 없는 100% 닭가슴살 동결건조 간식",
        "price": 14000,
        "category": "사료",
    },
    {
        "productId": 9,
        "name": "시니어견 관절 케어 사료 2kg",
        "description": "노령견 관절 보호를 위한 글루코사민·콘드로이틴 강화 사료",
        "price": 42000,
        "category": "사료",
    },
    {
        "productId": 10,
        "name": "강아지 자동 급수기",
        "description": "신선한 물을 순환 공급하는 자동 정수 급수기, 1.5L",
        "price": 32000,
        "category": "용품",
    },
    {
        "productId": 11,
        "name": "퍼피 훈련용 패드 50매",
        "description": "어린 강아지 배변 훈련을 위한 고흡수 패드",
        "price": 12000,
        "category": "용품",
    },
    {
        "productId": 12,
        "name": "강아지 치아 관리 덴탈 껌",
        "description": "치석 제거 및 구취 개선을 위한 천연 덴탈 껌 20개입",
        "price": 15000,
        "category": "건강관리",
    },
    {
        "productId": 13,
        "name": "대형견 이동용 캐리어",
        "description": "대형견을 위한 튼튼한 메쉬 소재 이동 가방, 통기성 우수",
        "price": 75000,
        "category": "용품",
    },
    {
        "productId": 14,
        "name": "강아지 슬리커 브러시",
        "description": "엉킨 털을 부드럽게 정리하는 전문 미용 브러시",
        "price": 13000,
        "category": "미용",
    },
    {
        "productId": 15,
        "name": "로프 터그 장난감",
        "description": "천연 면 소재로 안전한 줄다리기 놀이용 로프 장난감",
        "price": 9000,
        "category": "장난감",
    },
    {
        "productId": 16,
        "name": "강아지 오메가3 영양제",
        "description": "피부·털 윤기 개선을 위한 연어 오일 오메가3 60캡슐",
        "price": 26000,
        "category": "건강관리",
    },
    {
        "productId": 17,
        "name": "중형견 하네스 세트",
        "description": "중형견 체형에 맞는 안전 하네스 + 리드줄 세트, 내구성 강화 소재",
        "price": 28000,
        "category": "용품",
    },
    {
        "productId": 18,
        "name": "대형견 하네스 세트",
        "description": "대형견 체형에 맞는 튼튼한 하네스 + 리드줄 세트, 가슴·목 이중 고정",
        "price": 35000,
        "category": "용품",
    },
]
